game = "left4dead2.exe"

[[targets]]
name = "dwLocalPlayer"
signature = "8Bxxxxxxxxxxxx85xx74xx8Bxx8Bxxxxxxxxxx8BxxFFxx85xx74xx8Bxx"
module = "client.dll"
offset = 3
extra = 0

[[targets]]
name = "BaseOfHandgun"
signature = "0Dxxxxxxxxxxxx0FB7xx03xx03xx03xx8Bxxxx"
module = "server.dll"
offset = 1
extra = 0